# Generated by Django 4.2.16 on 2024-11-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_shippingaddress_number_alter_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обробці', 'В обробці'), ('Виконується', 'Виконується'), ('Виконано', 'Виконано'), ('Відмовлено', 'Відмовлено')], default='В обробці', max_length=20),
        ),
    ]
