# Generated by Django 4.2.16 on 2024-11-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(default='department', max_length=20, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Сплачено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обробці', 'В обробці'), ('Виконується', 'Виконується'), ('Виконано', 'Виконано'), ('Відмовлено', 'Відмовлено')], default='В обробці', max_length=20, verbose_name='Статус'),
        ),
    ]
