# Generated by Django 4.2.16 on 2024-11-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_delivery_type_alter_order_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(default='Доставка у відділення', max_length=20, verbose_name='Доставка'),
        ),
    ]
