# Generated by Django 4.2.16 on 2024-11-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_order_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(default='Доставка у відділення', max_length=100, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обробці', 'В обробці'), ('Виконується', 'Виконується'), ('Виконано', 'Виконано'), ('Відмовлено', 'Відмовлено')], default='В обробці', max_length=100, verbose_name='Статус'),
        ),
    ]
