# Generated by Django 4.2.16 on 2024-11-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_order_delivery_type_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'Адреса доставки', 'verbose_name_plural': 'Адреси доставки'},
        ),
    ]
