# Generated by Django 5.1.3 on 2024-11-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_order_options_alter_shippingaddress_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Відділення'),
        ),
    ]
