# Generated by Django 5.1.3 on 2025-05-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Обробляється', 'Обробляється'), ('Оплачено', 'Оплачено'), ('Відправлено', 'Відправлено'), ('Доставлено', 'Доставлено'), ('Скасовано', 'Скасовано')], default='pending', max_length=20),
        ),
    ]
