# Generated by Django 4.2.16 on 2024-11-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_imageslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('contact_info', models.CharField(max_length=255, verbose_name='Телефон/e-mail')),
                ('subject', models.CharField(choices=[('Замовлення', 'Замовлення'), ('Скарга', 'Скарга'), ('Пропозиція', 'Пропозиція'), ('Помилка', 'Помилка'), ('Інше', 'Інше')], max_length=100, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Повідомлення')),
            ],
        ),
    ]
