# Generated by Django 4.2.16 on 2024-11-11 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
