# Generated by Django 4.2.16 on 2024-11-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_contactrequest_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
            },
        ),
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'verbose_name': 'Звернення', 'verbose_name_plural': 'Звернення'},
        ),
        migrations.AlterModelOptions(
            name='imageslider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдери'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Оцінка', 'verbose_name_plural': 'Оцінки'},
        ),
    ]
