# Generated by Django 5.1.3 on 2024-11-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_image_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='picture',
            field=models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Зображення'),
        ),
    ]
